name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display .NET Version
        run: dotnet --info

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Stop IIS Website
        run: |
          Import-Module WebAdministration
          Stop-Website -Name "Quantasis-Day2-1"

      - name: Publish Application
        run: dotnet publish --configuration Release --no-build -o C:\Publish\Quantasis-Day2-1

      - name: Start IIS Website
        if: always()
        run: |
          Import-Module WebAdministration
          Start-Website -Name "Quantasis-Day2-1"
